### ISSUE TITLE
Filters on equipment on Crews page

### ISSUE THREAD

**Issue by Gedili** [solevis/pixyship#34]
On the Crews page, the filter for crews equips should be an AND, not an OR. If you select "Unique" and "Epic" on rarity for instance, then it'd show all the crews that satisfy any of those. For equips on the other hand you'd want the list that satifies both condition (having a head and a body item for example)

**Comment by solevis** [comment]
Yes, I'm still thinking about this feature because there are use case where the OR can be useful, for example you have an **Heavy Assault Armor** and a **Lucky Red Lantern** and you want to filter crew with **Rush** command that can fit this Body OR this Accessory and sort them by WPN stat, that will be impossible.

But in other side, if you want to get crew with this Body AND this Accessory, that's impossible now.

**Comment by Gedili** [comment]
All other the conditions are mutually exclusive (you can't be Epic and Hero, or have Poison Gas and Freeze, etc), so it definitely has to be an OR. For equips, I still think that the great majority of test scenarios will involved having an AND (both slots), rather than an OR (any of the slots). There might be a few counter examples, like the one you listed, but in that case if you programmed it as an AND, the user could always just check first the crews with Body and Rush, and then lookup those with Accessory and Rush. If you used and OR on the other hand, there'd be no way to have the conjunction, you'd have to go through the whole list and try identifying who has both. 

Ideally you could implement an option for both, adding "AND" and "OR" keywords in the filters for instance. But since of all the pages (crews, ships, items, etc) this field (equipment) is the only one in that case, I'm not sure it's worth the effort. Just using AND would be enough in my opinion.

**Comment by solevis** [comment]
Done in v2 😉
